'------------------------------------------------------------------------------
' <auto-generated>
'     O código foi gerado por uma ferramenta.
'     Versão de Tempo de Execução:4.0.30319.42000
'
'     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
'     o código for gerado novamente.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Funcionalidade de salvamento automático do My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.77;Initial Catalog=SGEDic_Demo_131108;Integrated Security=F"& _ 
            "alse;User ID=sa;Password=SAPWD")>  _
        Public ReadOnly Property SGEDic_Demo_131108ConnectionString() As String
            Get
                Return CType(Me("SGEDic_Demo_131108ConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.77;Initial Catalog=SGEDados_Demo_131108;Integrated Security"& _ 
            "=False;User ID=sa;Password=SAPWD")>  _
        Public ReadOnly Property SGEDados_Demo_131108ConnectionString() As String
            Get
                Return CType(Me("SGEDados_Demo_131108ConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Dsn=SGEDados_Demo_131108;uid=administrador;trusted_connection=Yes;app=Microsoft® "& _ 
            "Visual Studio® 2008;wsid=BAHIA-PC;database=SGEDados_Demo_131108")>  _
        Public ReadOnly Property SGEDados_Demo_131108ConnectionString1() As String
            Get
                Return CType(Me("SGEDados_Demo_131108ConnectionString1"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=ASP30;Initial Catalog=SGEDados_Demo;User ID=sa;Password=SAPWD")>  _
        Public ReadOnly Property SGEDados_DemoConnectionString() As String
            Get
                Return CType(Me("SGEDados_DemoConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=ASP30;Initial Catalog=SGEDados_Demo130809;User ID=sa;Password=SAPWD")>  _
        Public ReadOnly Property SGEDados_Demo130809ConnectionString() As String
            Get
                Return CType(Me("SGEDados_Demo130809ConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=ASP22;Initial Catalog=SGEDados_Demo;Integrated Security=True")>  _
        Public ReadOnly Property SGEDados_DemoConnectionString1() As String
            Get
                Return CType(Me("SGEDados_DemoConnectionString1"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=ASP22;Initial Catalog=SGEDados_Demo;Persist Security Info=True;User I"& _ 
            "D=sa;Password=SAPWD")>  _
        Public ReadOnly Property SGEDados_DemoConnectionString2() As String
            Get
                Return CType(Me("SGEDados_DemoConnectionString2"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=ASP22;Initial Catalog=SGEDados_Demo;User ID=sa")>  _
        Public ReadOnly Property SGEDados_DemoConnectionString3() As String
            Get
                Return CType(Me("SGEDados_DemoConnectionString3"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=ASP30;Initial Catalog=SGEDados_Demo;Persist Security Info=True;User I"& _ 
            "D=sa;Password=SAPWD")>  _
        Public ReadOnly Property SGEDados_DemoConnectionString4() As String
            Get
                Return CType(Me("SGEDados_DemoConnectionString4"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=ASP22;Initial Catalog=SGEDados_Demo;User ID=sa;Password=SAPWD")>  _
        Public ReadOnly Property SGEDados_DemoConnectionString5() As String
            Get
                Return CType(Me("SGEDados_DemoConnectionString5"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=ASP22;Initial Catalog=SGEDic_Demo;User ID=sa;Password=SAPWD")>  _
        Public ReadOnly Property SGEDic_DemoConnectionString() As String
            Get
                Return CType(Me("SGEDic_DemoConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=JONES-STI\SQLEXPRESS;Initial Catalog=SGEDic_Loja;Persist Security Inf"& _ 
            "o=True;User ID=sa;Password=SAPWD")>  _
        Public ReadOnly Property SGEDic_LojaConnectionString() As String
            Get
                Return CType(Me("SGEDic_LojaConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=JONES-STI\SQLEXPRESS;Initial Catalog=SGEDados_Loja;Persist Security I"& _ 
            "nfo=True;User ID=sa;Password=SAPWD")>  _
        Public ReadOnly Property SGEDados_LojaConnectionString() As String
            Get
                Return CType(Me("SGEDados_LojaConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=asp22;Initial Catalog=SGEDados1_Padrao_Oficial;User ID=sa;Password=SA"& _ 
            "PWD")>  _
        Public ReadOnly Property SGEDados1_Padrao_OficialConnectionString() As String
            Get
                Return CType(Me("SGEDados1_Padrao_OficialConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=ASP22;Initial Catalog=SGEDados1_Padrao_Oficial;User ID=sa;Password=SA"& _ 
            "PWD")>  _
        Public ReadOnly Property SGEDados1_Padrao_OficialConnectionString1() As String
            Get
                Return CType(Me("SGEDados1_Padrao_OficialConnectionString1"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/ws/cadconsultacadastro4.asmx")>  _
        Public ReadOnly Property sgenfebd4_cadconsultacadastro2_CadConsultaCadastro4() As String
            Get
                Return CType(Me("sgenfebd4_cadconsultacadastro2_CadConsultaCadastro4"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/ws/nfeconsultaprotocolo4.asmx")>  _
        Public ReadOnly Property sgenfebd4_nfeconsulta2_NFeConsultaProtocolo4() As String
            Get
                Return CType(Me("sgenfebd4_nfeconsulta2_NFeConsultaProtocolo4"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/ws/nfeinutilizacao4.asmx")>  _
        Public ReadOnly Property sgenfebd4_nfeinutilizacao2_NFeInutilizacao4() As String
            Get
                Return CType(Me("sgenfebd4_nfeinutilizacao2_NFeInutilizacao4"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/ws/nferetautorizacao4.asmx")>  _
        Public ReadOnly Property sgenfebd4_nferetautorizacao_NFeRetAutorizacao4() As String
            Get
                Return CType(Me("sgenfebd4_nferetautorizacao_NFeRetAutorizacao4"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/ws/nfestatusservico4.asmx")>  _
        Public ReadOnly Property sgenfebd4_nfestatusservico2_NFeStatusServico4() As String
            Get
                Return CType(Me("sgenfebd4_nfestatusservico2_NFeStatusServico4"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/ws/nferecepcaoevento4.asmx")>  _
        Public ReadOnly Property sgenfebd4_recepcaoevento_NFeRecepcaoEvento4() As String
            Get
                Return CType(Me("sgenfebd4_recepcaoevento_NFeRecepcaoEvento4"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/ws/nfeautorizacao4.asmx")>  _
        Public ReadOnly Property sgenfebd4_nfeautorizacao_NFeAutorizacao4() As String
            Get
                Return CType(Me("sgenfebd4_nfeautorizacao_NFeAutorizacao4"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.sgenfebd4.My.MySettings
            Get
                Return Global.sgenfebd4.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
